version: '3.1'
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
            interval: 10s
            timeout: 0s
            retries: 3
            start_period: 20s
        volumes:
            - mongo_data:/data/db
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: user
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://user:password@mongo:27017/
    # api:
    #     build: ./
    #     container_name: backend
    #     restart: always
    #     ports:
    #         - 3000:3000
    #     volumes:
    #         - /app/node_modules
    #         - ./:/app
    #     environment:
    #         - MONGO_USER=user
    #         - MONGO_PASSWORD=password
    #         - MONGO_HOST=mongo
    #         - MONGO_PORT=27017
    #         - MONGO_AUTHDATABASE=admin
    #         - SALT=10



volumes:
    mongo_data:
